-- ============================================================================
-- MODULA HEALTH — Migration 005: Evaluations, Plans, Documents, Consents
-- ============================================================================

-- EVALUATIONS (unified base table — type discriminator + JSONB metadata)
CREATE TABLE public.evaluations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    unit_id uuid NOT NULL REFERENCES public.units(id),
    client_id uuid NOT NULL REFERENCES public.client_profiles(id),
    professional_id uuid NOT NULL REFERENCES public.user_profiles(id),
    type evaluation_type NOT NULL,
    status evaluation_status NOT NULL DEFAULT 'draft',
    title varchar(200),
    scheduled_at timestamptz,
    started_at timestamptz,
    completed_at timestamptz,
    notes text,

    -- Type-specific data (physical: bodyComp, skinFolds; physio: painMap, ROM; etc.)
    metadata jsonb NOT NULL DEFAULT '{}',

    -- Summary generated by professional or AI
    summary text,
    ai_insights jsonb DEFAULT '{}',

    version integer NOT NULL DEFAULT 1,
    previous_version_id uuid REFERENCES public.evaluations(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL REFERENCES public.user_profiles(id)
);

CREATE TRIGGER evaluations_updated_at
    BEFORE UPDATE ON public.evaluations
    FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE INDEX idx_evaluations_tenant ON public.evaluations(tenant_id);
CREATE INDEX idx_evaluations_client ON public.evaluations(tenant_id, client_id);
CREATE INDEX idx_evaluations_prof ON public.evaluations(tenant_id, professional_id);
CREATE INDEX idx_evaluations_date ON public.evaluations(tenant_id, completed_at DESC);
CREATE INDEX idx_evaluations_physical ON public.evaluations(client_id, completed_at) WHERE type = 'physical';
CREATE INDEX idx_evaluations_physio ON public.evaluations(client_id, completed_at) WHERE type = 'physio';
CREATE INDEX idx_evaluations_nutrition ON public.evaluations(client_id, completed_at) WHERE type = 'nutrition';
CREATE INDEX idx_evaluations_metadata ON public.evaluations USING GIN(metadata);

-- PLANS (unified base — training, therapeutic, nutrition)
CREATE TABLE public.plans (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    unit_id uuid NOT NULL REFERENCES public.units(id),
    client_id uuid NOT NULL REFERENCES public.client_profiles(id),
    professional_id uuid NOT NULL REFERENCES public.user_profiles(id),
    evaluation_id uuid REFERENCES public.evaluations(id),
    type plan_type NOT NULL,
    status plan_status NOT NULL DEFAULT 'draft',
    title varchar(200) NOT NULL,
    description text,
    objectives text[],
    starts_at date,
    ends_at date,
    duration_weeks integer,

    -- Type-specific data
    metadata jsonb NOT NULL DEFAULT '{}',

    ai_generated boolean NOT NULL DEFAULT false,
    ai_insights jsonb DEFAULT '{}',

    version integer NOT NULL DEFAULT 1,
    previous_version_id uuid REFERENCES public.plans(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL REFERENCES public.user_profiles(id)
);

CREATE TRIGGER plans_updated_at
    BEFORE UPDATE ON public.plans
    FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE INDEX idx_plans_tenant ON public.plans(tenant_id);
CREATE INDEX idx_plans_client ON public.plans(tenant_id, client_id);
CREATE INDEX idx_plans_prof ON public.plans(tenant_id, professional_id);
CREATE INDEX idx_plans_status ON public.plans(tenant_id, status);
CREATE INDEX idx_plans_training ON public.plans(client_id, starts_at) WHERE type = 'training';
CREATE INDEX idx_plans_metadata ON public.plans USING GIN(metadata);

-- PROGRESS NOTES (session notes, evolution records — SOAP format for physio)
CREATE TABLE public.progress_notes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    unit_id uuid NOT NULL REFERENCES public.units(id),
    client_id uuid NOT NULL REFERENCES public.client_profiles(id),
    professional_id uuid NOT NULL REFERENCES public.user_profiles(id),
    plan_id uuid REFERENCES public.plans(id),
    evaluation_id uuid REFERENCES public.evaluations(id),
    type varchar(50) NOT NULL DEFAULT 'general',  -- general, soap, fitness, nutrition
    title varchar(200),

    -- SOAP fields (especially for physio)
    subjective text,
    objective text,
    assessment text,
    plan_notes text,       -- "plan" in SOAP
    general_notes text,    -- free-form notes for non-SOAP

    metadata jsonb NOT NULL DEFAULT '{}',

    session_date timestamptz NOT NULL DEFAULT now(),
    version integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL REFERENCES public.user_profiles(id)
);

CREATE TRIGGER progress_notes_updated_at
    BEFORE UPDATE ON public.progress_notes
    FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE INDEX idx_progress_notes_tenant ON public.progress_notes(tenant_id);
CREATE INDEX idx_progress_notes_client ON public.progress_notes(tenant_id, client_id);
CREATE INDEX idx_progress_notes_date ON public.progress_notes(tenant_id, session_date DESC);

-- DOCUMENTS (file attachments — exams, photos, contracts, reports)
CREATE TABLE public.documents (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    unit_id uuid REFERENCES public.units(id),
    client_id uuid REFERENCES public.client_profiles(id),
    uploaded_by uuid NOT NULL REFERENCES public.user_profiles(id),
    category document_category NOT NULL DEFAULT 'other',
    title varchar(200) NOT NULL,
    description text,
    file_name varchar(255) NOT NULL,
    file_path text NOT NULL,                      -- Supabase Storage path
    file_size bigint,
    mime_type varchar(100),
    sensitivity_level sensitive_level NOT NULL DEFAULT 'low',

    -- Optional links to entities
    evaluation_id uuid REFERENCES public.evaluations(id),
    plan_id uuid REFERENCES public.plans(id),

    tags text[] DEFAULT '{}',
    metadata jsonb NOT NULL DEFAULT '{}',
    is_archived boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER documents_updated_at
    BEFORE UPDATE ON public.documents
    FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE INDEX idx_documents_tenant ON public.documents(tenant_id);
CREATE INDEX idx_documents_client ON public.documents(tenant_id, client_id);
CREATE INDEX idx_documents_category ON public.documents(tenant_id, category);

-- CONSENT TEMPLATES (LGPD consent forms)
CREATE TABLE public.consent_templates (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid REFERENCES public.tenants(id) ON DELETE CASCADE,  -- NULL = system-wide
    title varchar(200) NOT NULL,
    content text NOT NULL,
    category varchar(50) NOT NULL,                -- 'data_processing', 'treatment', 'image_use', 'research'
    is_required boolean NOT NULL DEFAULT false,
    version integer NOT NULL DEFAULT 1,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER consent_templates_updated_at
    BEFORE UPDATE ON public.consent_templates
    FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE INDEX idx_consent_templates_tenant ON public.consent_templates(tenant_id);

-- CONSENT RECORDS (client's acceptance/revocation of consents)
CREATE TABLE public.consent_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    client_id uuid NOT NULL REFERENCES public.client_profiles(id),
    template_id uuid NOT NULL REFERENCES public.consent_templates(id),
    status consent_status NOT NULL DEFAULT 'pending',
    accepted_at timestamptz,
    revoked_at timestamptz,
    revocation_reason text,
    ip_address inet,
    user_agent text,
    signature_url text,
    metadata jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_consent_records_tenant ON public.consent_records(tenant_id);
CREATE INDEX idx_consent_records_client ON public.consent_records(tenant_id, client_id);
